Failure # 1 (occurred at 2025-04-21_14-07-28)
[36mray::ImplicitFunc.train()[39m (pid=14052, ip=127.0.0.1, actor_id=282632d4ccb060429756d8c801000000, repr=ray_train)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ian/1_Projects/hw/bioe145/final/.venv/lib/python3.12/site-packages/ray/tune/trainable/trainable.py", line 330, in train
    raise skipped from exception_cause(skipped)
  File "/Users/ian/1_Projects/hw/bioe145/final/.venv/lib/python3.12/site-packages/ray/air/_internal/util.py", line 107, in run
    self._ret = self._target(*self._args, **self._kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ian/1_Projects/hw/bioe145/final/.venv/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ian/1_Projects/hw/bioe145/final/.venv/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py", line 261, in _trainable_func
    output = fn()
             ^^^^
  File "/var/folders/26/0017yn4d4515d4_v5jg7653m0000gn/T/ipykernel_13149/1633563901.py", line 19, in ray_train
  File "/var/folders/26/0017yn4d4515d4_v5jg7653m0000gn/T/ipykernel_13149/2398578195.py", line 9, in epoch_train
NameError: name 'optimizer' is not defined
